In [1]:
import numpy as np
import time

from sympy.strategies.branch import condition

### Creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("1D Array: \n", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: \n", arr_2d)

1D Array: 
 [1 2 3 4 5 6]
2D Array: 
 [[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [3]:
py_list = [1, 2, 3]
print("Python List Multiplication: ", py_list * 3)

np_arr = np.array([1, 2, 3])  # Element wise multiplication.
print("Numpy Array Multiplication: ", np_arr * 3)

# Efficiency
start = time.time()
py_list = [i * 3 for i in range(1000000)]
print("List Multiplication Operation time: ", time.time() - start)

start = time.time()
np_arr = np.arange(1, 1000000, 1) * 2
print("Numpy Multiplication time: ", time.time() - start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3, 1, 2, 3]
Numpy Array Multiplication:  [3 6 9]
List Multiplication Operation time:  0.03744173049926758
Numpy Multiplication time:  0.0024917125701904297


### Creating array from scratch

In [4]:
zeros = np.zeros([3, 4])
print("Zeros Array: \n", zeros)

ones = np.ones([3, 4])
print("Ones Array: \n", ones)

full = np.full([3, 4], 7)
print("Full Array: \n", full)

random = np.random.random([3, 4])  # Always between 0 and 1
print("Random Array: \n", random)

sequence = np.arange(1, 11, 2)
print("Sequence Array: \n", sequence)

randomInt = np.random.randint(1, 101, size=(3, 4))
print("Random Int Array: \n", randomInt)

Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array: 
 [[0.34510488 0.38515209 0.98537952 0.21508626]
 [0.10957397 0.57873036 0.84036861 0.53140488]
 [0.0262705  0.68914623 0.92888735 0.09749764]]
Sequence Array: 
 [1 3 5 7 9]
Random Int Array: 
 [[97 68 73 55]
 [92 92 72 84]
 [53 28 58 25]]


### Vector, Matrices & Tensor

In [5]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Arr: \n", arr)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)  # Number of Element
print("Data Type: ", arr.dtype)

Arr: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


### Array Reshaping

In [7]:
arr = np.arange(1, 13)
print("Original Array: \n", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped Array: \n", reshaped)

flattened = arr.flatten()
print("Flattened Array: \n", flattened)

raveled = reshaped.ravel()  # Return view, instead of copy
print("Raveled Array: \n", raveled)

transposed = reshaped.T
print("Transposed Array: \n", transposed)

Original Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transposed Array: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Array concatenation & stacking

In [8]:
arr1 = np.arange(1, 11)
arr2 = np.arange(11, 21)

combined = arr1 + arr2  # It will add the element of both the array at a particular index
combined = np.concatenate((arr1, arr2))
print("Combined Array: \n", combined)

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
concatenated_array_row = np.concatenate((arr1, arr2), axis=0)  # axis 0 = row
print("Concatenated Array (Rows):\n", concatenated_array_row)
concatenated_array_column = np.concatenate((arr1, arr2), axis=1)  # axis 1 = column
print("Concatenated Array (Columns):\n", concatenated_array_column)

# Stack horizontally
stacked_array_h = np.hstack((arr1, arr2))
print("Stacked Horizontally:\n", stacked_array_h)

# Stack vertically
stacked_array_v = np.vstack((arr1, arr2))
print("Stacked Vertically:\n", stacked_array_v)



Combined Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Concatenated Array (Rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated Array (Columns):
 [[1 2 5 6]
 [3 4 7 8]]
Stacked Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]
Stacked Vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### NumPy Array Operations

#### Slicing & Negative indexing

In [9]:
arr = np.arange(1, 11)
print("Original Array: \n", arr)
print("Basic Slicing: \n", arr[2:8])
print("Slicing with steps: \n", arr[2:8:2])
print("Negative Indexing: \n", arr[-5])

Original Array: 
 [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing: 
 [3 4 5 6 7 8]
Slicing with steps: 
 [3 5 7]
Negative Indexing: 
 6


### Specific Element, Row & Column

In [10]:
arr_2d = np.arange(1, 10).reshape((3, 3))
print("2D Array: \n", arr_2d)

print("Specific element: ", arr_2d[2, 1])
print("Entire row: \n", arr_2d[1])
print("Entire Column: \n", arr_2d[:, 2])

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  8
Entire row: 
 [4 5 6]
Entire Column: 
 [3 6 9]


### Sorting

In [11]:
unsorted_arr = np.random.randint(10, size=5)
print("Original Array: \n", unsorted_arr)
print("Sorted Array: \n", np.sort(unsorted_arr))

unsorted_arr_2d = np.random.randint(10, size=(3, 3))
print("Original 2D Array: \n", unsorted_arr_2d)
print("Sorted 2D Array (Column): \n", np.sort(unsorted_arr_2d, axis=0))  # Sorting column-wise
print("Sorted 2D Array (Row): \n", np.sort(unsorted_arr_2d, axis=1))  # Sorting row-wise

Original Array: 
 [9 4 8 5 9]
Sorted Array: 
 [4 5 8 9 9]
Original 2D Array: 
 [[8 9 7]
 [3 5 0]
 [4 1 9]]
Sorted 2D Array (Column): 
 [[3 1 0]
 [4 5 7]
 [8 9 9]]
Sorted 2D Array (Row): 
 [[7 8 9]
 [0 3 5]
 [1 4 9]]


### Filtering

In [12]:
numbers = np.arange(1, 11)
print("Numbers Array: \n", numbers)

even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: \n", even_numbers)

Numbers Array: 
 [ 1  2  3  4  5  6  7  8  9 10]
Even Numbers: 
 [ 2  4  6  8 10]


### Filtering with mask

In [13]:
mask = numbers > 5
print("Numbers greater than 5: \n", numbers[mask])

Numbers greater than 5: 
 [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [14]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers % 3 == 0)
print("Where Result: \n", where_result)
print("NP Where Result: \n", numbers[where_result])

[1 3 5]
Where Result: 
 (array([2, 5, 8]),)
NP Where Result: 
 [3 6 9]


### Condition array using np.where()

In [15]:
condition_array = np.where(numbers > 5, numbers * 4,
                           numbers - 4)  # Same as if numbers > 5: numbers *= 4 else: numbers -= 4
print("Condition Array: \n", condition_array)

Condition Array: 
 [-3 -2 -1  0  1 24 28 32 36 40]


### Compatibility

In [16]:
arr1 = np.arange(1, 11)
arr2 = np.arange(11, 21)
arr3 = np.arange(21, 31)

print("Compatibility Shapes: ", arr1.shape == arr2.shape == arr3.shape)

Compatibility Shapes:  True


### Vertical Stacking & Horizontal Stacking

In [17]:
original = np.arange(1,10).reshape((3,3))
row = np.array([10,11,12])
col = np.array([[10],[11],[12]])

with_new_row = np.vstack((original, row))
print("Array with new row: \n", with_new_row)

with_new_column = np.hstack((original, col))
print("Array with new column: \n", with_new_column)

Array with new row: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Array with new column: 
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


### Delete operation

In [18]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,3)
print("Array after deletion: \n", deleted)

Array after deletion: 
 [1 2 3 5]
