In [35]:
import numpy as np
import time

### Creating array from list

In [36]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("1D Array: \n", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: \n", arr_2d)

1D Array: 
 [1 2 3 4 5 6]
2D Array: 
 [[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [37]:
py_list = [1, 2, 3]
print("Python List Multiplication: ", py_list * 3)

np_arr = np.array([1, 2, 3])  # Element wise multiplication.
print("Numpy Array Multiplication: ", np_arr * 3)

# Efficiency
start = time.time()
py_list = [i * 3 for i in range(1000000)]
print("List Multiplication Operation time: ", time.time() - start)

start = time.time()
np_arr = np.arange(1, 1000000, 1) * 2
print("Numpy Multiplication time: ", time.time() - start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3, 1, 2, 3]
Numpy Array Multiplication:  [3 6 9]
List Multiplication Operation time:  0.05077505111694336
Numpy Multiplication time:  0.004322052001953125


### Creating array from scratch

In [38]:
zeros = np.zeros([3, 4])
print("Zeros Array: \n", zeros)

ones = np.ones([3, 4])
print("Ones Array: \n", ones)

full = np.full([3, 4], 7)
print("Full Array: \n", full)

random = np.random.random([3, 4])  # Always between 0 and 1
print("Random Array: \n", random)

sequence = np.arange(1, 11, 2)
print("Sequence Array: \n", sequence)

randomInt = np.random.randint(1, 101, size=(3, 4))
print("Random Int Array: \n", randomInt)

Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array: 
 [[0.88018981 0.16347902 0.65439014 0.59990976]
 [0.9915404  0.68357846 0.47613818 0.90848414]
 [0.43963067 0.10525807 0.5465292  0.90248321]]
Sequence Array: 
 [1 3 5 7 9]
Random Int Array: 
 [[24 59 32 48]
 [78 72  7 40]
 [50 56 53 67]]


### Vector, Matrices & Tensor

In [39]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties

In [40]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Arr: \n", arr)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)  # Number of Element
print("Data Type: ", arr.dtype)

Arr: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


### Array Reshaping

In [41]:
arr = np.arange(1, 13)
print("Original Array: \n", arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array: \n", reshaped)

flattened = arr.flatten()
print("Flattened Array: \n", flattened)

raveled = reshaped.ravel()      # Return view, instead of copy
print("Raveled Array: \n", raveled)

transposed = reshaped.T
print("Transposed Array: \n", transposed)

Original Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transposed Array: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
